Backend/AspNetCoreAssessment/AspNetCoreAssessment/Entities/Documents.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AspNetCoreAssessment.Entities
{
    public partial class Documents
    {
        public Documents()
        {
            DocumentFiles = new HashSet<DocumentFiles>();
        }

        public int DocumentId { get; set; }
        public string Name { get; set; }
        public DateTime Created { get; set; }
        public DateTime Date { get; set; }
        public int Priority { get; set; }
        public DateTime DueDate { get; set; }

        public virtual Priorities PriorityNavigation { get; set; }
        public virtual ICollection<DocumentFiles> DocumentFiles { get; set; }
    }
}

Backend/AspNetCoreAssessment/AspNetCoreAssessment/Controllers/DocumentController.cs
using AspNetCoreAssessment.Manger;
using AspNetCoreAssessment.Models;
using Microsoft.AspNetCore.Mvc;

namespace AspNetCoreAssessment.Controllers
{
    public class DocumentController : Controller    
    {
        private readonly DocumentManger documentManger;
        private readonly PriorityManger priorityManger;

        public DocumentController(DocumentManger documentManger, PriorityManger priorityManger)
        {
            this.documentManger = documentManger;
            this.priorityManger = priorityManger;
        }
        [HttpGet]
        public IActionResult Index(string Msg)
        {
            if(!string.IsNullOrEmpty(Msg))
            {
            ViewBag.Msg = Msg;

            }
            return View();
        }
        [HttpGet]
        public IActionResult upload()
        {
            ViewBag.PrioritiesSelectList = priorityManger.GetAllPriorities();

            return View();
        }
        [HttpPost]
        public IActionResult upload(DocumentVM documentVM)
        {
            ViewBag.PrioritiesSelectList = priorityManger.GetAllPriorities();

            if(ModelState.IsValid)
            {
                if(documentVM.DocumentFiles == null)
                {
                    ModelState.AddModelError("", "At Least Upload one file");
                    ViewBag.PrioritiesSelectList = priorityManger.GetAllPriorities();
                    return View();
                }
                documentManger.UploadDocument(documentVM);
                Redirect("/Document#AvalableDocs?Msg=UploadSuccess#Msg");

            }
            return View();
        }
        [HttpGet]
        public IActionResult details(int Id=0)
        {
            if(Id==0)
            {
                return Redirect("/Document?Msg=NoDocument#Msg");
            }
            var data = documentManger.GetDocumentById(Id);
            return View(data);
        }
        [HttpGet]
        public IActionResult update(int Id = 0)
        {            
            ViewBag.PrioritiesSelectList = priorityManger.GetAllPriorities();

            if (Id == 0)
            {
                return Redirect("/Document?Msg=NoDocument#Msg");
            }
            var data = documentManger.GetDocumentById(Id);
            return View(data);
        }
        [HttpPost]
        public IActionResult update(DocumentVM documentVM)
        {
            ViewBag.PrioritiesSelectList = priorityManger.GetAllPriorities();

            if (ModelState.IsValid)
            {
                documentManger.UpdateDocument(documentVM);
                return Redirect("/Document?Msg=UpdatedSuccessfuly#Msg");

            }
            return View();
        }
        [HttpGet]
        public IActionResult delete(int Id = 0)
        {
            if (Id == 0)
                return Redirect("/Document?Msg=NoDocument#Msg");
            documentManger.DeleDocument(Id);
            return Redirect("/Document?Msg=DeletedSuccessfuly#Msg");
        }

    }
}

Backend/AspNetCoreAssessment/AspNetCoreAssessment/Views/Document/Index.cshtml
@model AspNetCoreAssessment.Models.DocumentVM
@{
    ViewData["Title"] = "Available documents";
}
<link href="/lib/datatables/css/dataTables.bootstrap4.css" rel="stylesheet" />
<br />
<br />
<div class="container" >
<!-- Inputs -->
    <h3 id="AvalableDocs">Available documents</h3>
    @if (ViewBag.Msg != null)
    {
        <div class="alert alert-primary alert-dismissible fade show" role="alert" >
        @if (ViewBag.Msg == "NoDocument")
        {
                <p>Please select a document to see its information</p>

            }
            else if (ViewBag.Msg == "DeletedSuccessfuly")
            {
                <p>The document Information and folder were Deleted successfuly</p>

            }else if (ViewBag.Msg == "UpdatedSuccessfuly")
            {
                <p>Document information Updated successfuly</p>
            }
            else if (ViewBag.Msg == "UploadSuccess")
            {
                <p>Document Uploaded successfuly</p>
            }
       
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
        </div>
    }
<hr>
    <div class="row">
        <div class="col-sm-12 margin-bottom30">
            <table id="DocumentList" class="table table-striped table-bordered dt-responsive nowrap">
                <thead>
                    <tr>
                        <th>Document Name</th>
                        <th>Uploaded date</th>
                        <th>Date</th>
                        <th>Priority</th>
                        <th>Due Date</th>
                        <th>Details</th>
                        <th>Update</th>
                        <th>delete</th>
                    </tr>

                </thead>
            </table>
        </div><!--services col-->

    </div>
</div>
@section _DocumenDatatable
    {
    <script src="/lib/datatables/js/jquery.dataTables.js"></script>
    <script src="/lib/datatables/js/dataTables.bootstrap4.js"></script>
    <script type="text/javascript" src="/js/DocumentsDatatable.js"></script>

    
        }

Backend/AspNetCoreAssessment/AspNetCoreAssessment/Views/Document/details.cshtml
@model AspNetCoreAssessment.Models.DocumentVM
@{
    ViewData["Title"] = "Document information";
}




<br />
<br />
<div class="container" id="DocDetails">
    <!-- Inputs -->
    <h3>Document information</h3>
    <hr>

        <div class="row mt-5">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Name"></label>
                    <input type="text" class="form-control" asp-for="Name"  disabled>
                    <br />
                </div>
                <div class="form-group">
                    <label >Created date</label>
                    <input type="text" asp-for="Created" class="form-control" disabled>
                    <br />
                </div>
                <div class="form-group">
                    <label asp-for="Date"></label>
                <input type="text" asp-for="Date" class="form-control" disabled>
                    <br />
                </div>

                <div class="form-group">
                    <label asp-for="PriorityName.Name"></label>
                <input type="text" asp-for="PriorityName.Name" class="form-control" disabled>

                    <br />

                </div>
                <div class="form-group">
                    <label >Due Date</label>
                    <input type="text" asp-for="DueDate" class="form-control" disabled>
                    <br />
                </div>
                <br />
                <div class="form-group">
                <a class=" btn btn-primary" href="/Document/update?Id=@Model.DocumentId" style="float:right">Upload a Document</a>
            </div>
               
            </div>

        </div> <!-- end of inputs -->

</div>
@section _ValidationScript
    {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
 }

Backend/AspNetCoreAssessment/AspNetCoreAssessment/Views/Document/update.cshtml
@model AspNetCoreAssessment.Models.DocumentVM

@{
    ViewData["Title"] = "Update Document";
}



<br />
<br />
<div class="container" id="UploadDocument">
    <!-- Inputs -->
    <h3>Upload a document</h3>
    <hr>
    <form method="post" asp-controller="Document" asp-action="update">
        <input type="hidden" asp-for="DocumentId"/>
        <input type="hidden" asp-for="Created" />

        <div class="row mt-5">
            <div class="col-md-12">
                <div asp-validation-summary="All" style="color:red"></div>
                <div class="form-group">
                    <label asp-for="Name"></label>
                    <input type="text" class="form-control" asp-for="Name" placeholder="Document name">
                    <br />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Date"></label>
                    <input type="datetime-local" asp-for="Date" class="form-control">
                    <br />
                    <span asp-validation-for="Date" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Priority"></label>
                    <select class="form-control" asp-for="Priority">

                        <option disabled selected value="0">choose a priority</option>
                        @foreach (var item in ViewBag.PrioritiesSelectList)
                        {
                            <option value="@item.Id">@item.Name</option>
                        }


                    </select>
                    <br />
                    <span asp-validation-for="Priority" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DueDate"></label>
                    <input type="datetime-local" asp-for="DueDate" class="form-control">
                </div>
                <br />
                <div class="form-group">
                    <input type="submit" class="btn btn-primary" value="Update Information" style="float:right" />
                </div>
            </div>

        </div> <!-- end of inputs -->
    </form>
</div>
@section _ValidationScript
    {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
 }

Backend/AspNetCoreAssessment/AspNetCoreAssessment/Views/Document/upload.cshtml
@model AspNetCoreAssessment.Models.DocumentVM
@{
    ViewData["Title"] = "Upload a document";
}
<br />
<br />
<div class="container" id="UploadDocument">
    <!-- Inputs -->
    <h3 >Upload a document</h3>
    <hr>
    <form method="post" asp-controller="Document" asp-action="upload" enctype="multipart/form-data">
        <div class="row mt-5">
            <div class="col-md-12">
                <div asp-validation-summary="All" style="color:red"></div>
                <div class="form-group">
                    <label asp-for="Name"></label>
                    <input type="text" class="form-control" asp-for="Name" placeholder="Document name" autocomplete="off">
                    <br />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Date"></label>
                    <input type="datetime-local" asp-for="Date" class="form-control" autocomplete="off">
                    <br />
                    <span asp-validation-for="Date" class="text-danger"></span>
                </div>
                    
                <div class="form-group">
                    <label asp-for="Priority"></label>
                    <select class="form-control" asp-for="Priority" >

                        <option disabled selected value="0">choose a priority</option>
                        @foreach (var item in ViewBag.PrioritiesSelectList)
                        {
                            <option value="@item.Id">@item.Name</option>
                        }
                        
                        
                    </select>
                    <br />
                    <span asp-validation-for="Priority" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DueDate"></label>
                    <input type="datetime-local" asp-for="DueDate" class="form-control" autocomplete="off">
                </div>
                <div class="form-group">
                    <label asp-for="DocumentFiles"></label>
                    <input type="file" multiple  class="form-control form-control-lg" asp-for="DocumentFiles" />
                    <br />
                    <span asp-validation-for="DocumentFiles" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group">
                    <input type="submit" class="btn btn-primary" value="Upload" style="float:right"/>
                </div>
            </div>
         
        </div> <!-- end of inputs -->
    </form>
</div>
@section _ValidationScript
{
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
 }